---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: "Install Java"
      command: yum install java -y
    - name: "Downloading Jenkins from Public Jenkins repository"
      command: sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
    - name: "Downloading 1"
      command: sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    - name: "Installing Jenkins dependency package called epel"
      command: sudo amazon-linux-extras install epel -y
    - name: "Installing Jenkins"
      command: yum install jenkins -y
    - name: "Starting Jenkins service"
      command: service jenkins start
    - name: "checking Jenkins service status"
      command: service jenkins status
      register: catboyy
    - name: "Displaying Jenkins service status"
      debug: var=catboyy.stdout_lines
    - name: "Checking the Jenkins default admin password"
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: battboy
    - name: "Displaying default admin password"
      debug: var=battboy.stdout_lines
    - name: "Downloading Maven package" 
      shell: "wget https://dlcdn.apache.org/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz"
      args:
          chdir: /opt
    - name: "Untaring the file"
      command: tar -xvzf /opt/apache-maven-3.8.4-bin.tar.gz
      args:
          chdir: /opt
    - name: "Renaming the apache-maven-3.8.4 to maven"
      command: mv apache-maven-3.8.4 maven 
      args:
          chdir: /opt
    - name: "Installing Git"
      command: yum install git -y
      args:
          chdir: /opt

